init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- cd src
- nuget restore

image: Visual Studio 2019

build:
  verbosity: minimal
  
after_test:
  - cd .\LogoFX.Client.Mvvm.Model.Specs\bin
  - livingdoc test-assembly LogoFX.Client.Mvvm.Model.Specs.dll -t TestExecution.json --work-item-url-template https://github.com/LogoFX/logofx-client-mvvm-model/issues/{id} --work-item-prefix WI
    