version: 2.2.0.{build}

init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- cd src
- nuget restore

image: Visual Studio 2019

build:
  verbosity: minimal
  project: ./src/LogoFX.Client.Mvvm.Model.sln

test_script:
  - cd
  - cd ../devops/test
  - test.bat
  - cd ../../

after_test:
  - cd ./devops
  - cd pack
  - pack

artifacts:
  - name: Packages
    path: ./output/*.nupkg

  - name: Living Documentation
    path: ./src/LogoFX.Client.Mvvm.Model/bin/LivingDoc.html
  