init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- cd src
- nuget restore

image: Visual Studio 2019

build:
  verbosity: minimal
  
test_script:
  - cd
  - cd ..\devops\test
  - test.bat
  - cd ..\..\
    
artifacts:

  # pushing a single file
  - path: .\src\LogoFX.Client.Mvvm.Model.Specs\bin\LivingDoc.html